# Backend Dockerfile
FROM node:14-alpine

# Set the working directory for the backend
WORKDIR /app/backend

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install backend dependencies
RUN npm install --production

# Copy the rest of the backend files to the container
COPY . .

# Expose the port on which the server should run (5000 for backend)
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
