version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
